<?php

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "api" middleware group. Make something great!
|
*/

/* Route::middleware('auth:sanctum')->get('/user', function (Request $request) {
    return $request->user();
}); */
/* Route::post('/user', function (Request $request) {
    $user = User::get();
    return response()->json([
        'data' => $user    ]);
}); */

Route::post('/login', function (Request $request) {
    if(empty($request->email)){
        return response()->json([
            'status' => false,
            'message' => 'Email Required!',
        ]);
    }
    return response()->json([
        'email' => $request->email,
        'password' => $request->password,
    ]);
});
Route::get('/imran/test', function (Request $request) {
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://apiv2.allsportsapi.com/cricket/?met=Leagues&APIkey=241e93281f895b0c4d150ef8ecb8c303ca6902d047ef33cda4f09cfa9396a37b');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);

    echo $result;
});